### ISSUE TITLE
Admin Crosslist Tool: Search for instructors

### ISSUE THREAD

**Issue by mlisle** [sukotsuchido/CanvasUserScripts#2]
I'm trying to test these scripts out using Tampermonkey with our instance, and the user script is working fine. However, I'm not able to get the admin crosslist tool to work. 

When I search for teachers' names, I get a loading indicator with no search results. Is there a trick to getting the admin crosslist tool to work? I'm using V 1.6 "KatyISD Instructor and Admin Crosslisting Tools".

![screen shot 2018-01-04 at 10 44 49 am](https://user-images.githubusercontent.com/14081049/34571388-67040096-f13c-11e7-8f73-b8b541cb1841.png)

**Comment by sukotsuchido** [comment]
Howdy, I'm sorry I'm just now seeing this - I didn't have notifications for issues set to email me. I've updated both scripts that contain the admin panel. If you are still having issues, let me know.
