### ISSUE TITLE
Check boxes covered by Canvas Pane in Course Event Manager

### ISSUE THREAD

**Issue by AlexChristensen** [sukotsuchido/CanvasUserScripts#4]
## Function with issue:

Course Event Manager

## Description of issue:

Canvas has an irremovable pane on the left-hand side of the screen that covers the check boxes for selecting calendar dates to remove.

## Behavior I'd like to see:

The check boxes and selection boxes for "Selected events:" to be shifted to the right and away from the Canvas pane

Thank you

**Comment by larsvemund** [comment]
Hi,
Got this to work but had to set "run in" = Document-body.

**Comment by AlexChristensen** [comment]
@larsvemund, perfect. Thank you!
